polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # path("", views.index, name="index"),
    path("admin/", views.login, name='login'),
    path("admin/logout", views.logout_request, name='logout'),
    path("admin/home/", views.home, name='home'),
    path("admin/profile", views.get_profile, name='get_profile'),


]

web_clothings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clothing/', include('polls.urls'))
]

polls/models.py
from django.db import models

from polls import CompositeAutoField


# Create your models here.
class UserStatus(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=255)
    create_date = models.DateTimeField(auto_now_add=True, editable=False)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'user_status'


class Role(models.Model):
    id = models.BigAutoField(primary_key=True),
    name = models.CharField(max_length=255),
    create_date = models.DateTimeField(auto_now_add=True, editable=False)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'role'


class User(models.Model):
    id = CompositeAutoField(
        prefix='UE',
        max_length=15,
        primary_key=True

    )
    first_name = models.CharField(max_length=255),
    last_name = models.CharField(max_length=255),
    email = models.CharField(max_length=255),
    phone_number = models.CharField(max_length=12),
    customer_status = models.ForeignKey(UserStatus, on_delete=models.CASCADE, related_name='user'),
    role = models.ForeignKey(Role, on_delete=models.CASCADE, related_name='role'),
    create_date = models.DateTimeField(auto_now_add=True, editable=False)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'user'


class ProductType(models.Model):
    id = models.BigAutoField(primary_key=True),
    name = models.CharField(max_length=255),
    create_date = models.DateTimeField(auto_now_add=True, editable=False)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'product_type'


class ProductStatus(models.Model):
    id = models.BigAutoField(primary_key=True),
    name = models.CharField(max_length=255),
    create_date = models.DateTimeField(auto_now_add=True, editable=False)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'product_status'


class SkuItem(models.Model):
    id = models.BigAutoField(primary_key=True),
    name = models.CharField(max_length=255),
    invalid = models.BooleanField(default=False)
    create_date = models.DateTimeField(auto_now_add=True, editable=False)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'sku_item'


class Product(models.Model):
    id = CompositeAutoField(
        prefix='PD',
        max_length=15,
        primary_key=True

    )
    name = models.CharField(max_length=255),
    description = models.TextField(),
    product_type = models.ForeignKey(ProductType, on_delete=models.CASCADE, related_name='product-type'),
    product_status = models.ForeignKey(ProductStatus, on_delete=models.CASCADE, related_name='product-status'),
    note = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True, editable=False)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'product'


class ProductImage(models.Model):
    id = models.BigAutoField(primary_key=True),
    sort_no = models.IntegerField(),
    file_name = models.CharField(255),
    create_date = models.DateTimeField(auto_now_add=True, editable=False)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'product_image'


class SkuSetItem(models.Model):
    id = models.BigAutoField(primary_key=True),
    sku_item = models.ForeignKey(SkuItem, on_delete=models.CASCADE, related_name='sku_item'),
    name = models.CharField(max_length=255),
    invalid = models.BooleanField(default=False),
    create_date = models.DateTimeField(auto_now_add=True, editable=False)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'sku_set_item'


class ProductSku(models.Model):
    id = CompositeAutoField(
        prefix='SK',
        max_length=15,
        primary_key=True

    )
    sku_set_item1 = models.ForeignKey(SkuSetItem, on_delete=models.CASCADE, related_name='sku-set-item'),
    sku_set_item2 = models.ForeignKey(SkuSetItem, on_delete=models.CASCADE, related_name='sku-set-item'),
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE),
    stock = models.IntegerField(),
    price = models.IntegerField()
    create_date = models.DateTimeField(auto_now_add=True, editable=False)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'product_sku'

polls/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")

### Trang chủ admin -
def home(request):
    return render(request, 'polls/admin/index.html')


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return HttpResponseRedirect(reverse("polls:home"))
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="polls/admin/login.html", context={"login_form": form})


def logout_request(request):
    logout(request)
    return render(request, 'polls/admin/login.html', messages.error(request, "You have successfully logged out."))


def get_profile(request):
    return render(request, 'polls/admin/profile.html')

polls/templates/polls/admin/include/footer.html
{% load static %}
<div class="">
    <p class="pull-right">Gentelella Alela! a Bootstrap 3 template by <a>Kimlabs</a>. |
        <span class="lead"> <i class="fa fa-paw"></i> Gentelella Alela!</span>
    </p>
</div>
<div class="clearfix"></div>

polls/templates/polls/admin/include/header.html
{% load static %}
<div class="nav_menu">
    <nav class="" role="navigation">
        <div class="nav toggle">
            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
        </div>

        <ul class="nav navbar-nav navbar-right">
            <li class="">
                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                   aria-expanded="false">
                    <img src="{% static 'polls/admin/images/img.jpg' %}" alt="">Hi
                    <span class=" fa fa-angle-down"></span>
                </a>
                <ul class="dropdown-menu dropdown-usermenu animated fadeInDown pull-right">
                    <li><a href="javascript:;"> Profile</a>
                    </li>
                    <li>
                        <a href="javascript:;">
                            <span class="badge bg-red pull-right">50%</span>
                            <span>Settings</span>
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;">Help</a>
                    </li>
                    <li><a href="{% url 'polls:logout' %}"><i class="fa fa-sign-out pull-right"></i> Log Out</a>
                    </li>
                </ul>
            </li>

            <li role="presentation" class="dropdown">
                <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-envelope-o"></i>
                    <span class="badge bg-green">6</span>
                </a>
                <ul id="menu1" class="dropdown-menu list-unstyled msg_list animated fadeInDown" role="menu">
                    <li>
                        <a>
                                            <span class="image">
                                        <img src="images/img.jpg" alt="Profile Image"/>
                                    </span>
                            <span>
                                        <span>John Smith</span>
                                            <span class="time">3 mins ago</span>
                                            </span>
                            <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
                        </a>
                    </li>
                    <li>
                        <a>
                                            <span class="image">
                                        <img src="images/img.jpg" alt="Profile Image"/>
                                    </span>
                            <span>
                                        <span>John Smith</span>
                                            <span class="time">3 mins ago</span>
                                            </span>
                            <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
                        </a>
                    </li>
                    <li>
                        <a>
                                            <span class="image">
                                        <img src="images/img.jpg" alt="Profile Image"/>
                                    </span>
                            <span>
                                        <span>John Smith</span>
                                            <span class="time">3 mins ago</span>
                                            </span>
                            <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
                        </a>
                    </li>
                    <li>
                        <a>
                                            <span class="image">
                                        <img src="{% static 'polls/admin/images/img.jpg' %}" alt="Profile Image"/>
                                    </span>
                            <span>
                                        <span>John Smith</span>
                                            <span class="time">3 mins ago</span>
                                            </span>
                            <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
                        </a>
                    </li>
                    <li>
                        <div class="text-center">
                            <a>
                                <strong><a href="inbox.html">See All Alerts </strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>
                    </li>
                </ul>
            </li>

        </ul>
    </nav>
</div>

polls/templates/polls/admin/include/link_lib.html
{% load static %}
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<!-- Meta, title, CSS, favicons, etc. -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>Gentallela Alela! | </title>

<!-- Bootstrap core CSS -->

<link href="{% static 'polls/admin/css/bootstrap.min.css' %}" rel="stylesheet">

<link href="{% static 'polls/admin/fonts/css/font-awesome.min.css' %}" rel="stylesheet">
<link href="{% static 'polls/admin/css/animate.min.css' %}" rel="stylesheet">

<!-- Custom styling plus plugins -->
<link href="{% static 'polls/admin/css/custom.css' %}" rel="stylesheet">
<link href="{% static 'polls/admin/css/icheck/flat/green.css' %}" rel="stylesheet">


<script src="{% static 'polls/admin/js/jquery.min.js' %}"></script>

<!--[if lt IE 9]>
<script src="../assets/js/ie8-responsive-file-warning.js"></script>
<![endif]-->

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

polls/templates/polls/admin/include/slidemenu.html
{% load static %}
<div class="left_col scroll-view">

    <div class="navbar nav_title" style="border: 0;">
        <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Gentellela Alela!</span></a>
    </div>
    <div class="clearfix"></div>

    <!-- menu prile quick info -->
    <div class="profile">
        <div class="profile_pic">
            <img src="images/img.jpg" alt="..." class="img-circle profile_img">
        </div>
        <div class="profile_info">
            <span>Welcome,</span>
            <h2>Anthony Fernando</h2>
        </div>
    </div>
    <!-- /menu prile quick info -->

    <br/>

    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

        <div class="menu_section">
            <h3>General</h3>
            <ul class="nav side-menu">
                <li><a href="index.html"><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                </li>
                <li><a><i class="fa fa-edit"></i> Forms <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu" style="display: none">
                        <li><a href="form.html">General Form</a>
                        </li>
                        <li><a href="form_advanced.html">Advanced Components</a>
                        </li>
                        <li><a href="form_validation.html">Form Validation</a>
                        </li>
                        <li><a href="form_wizards.html">Form Wizard</a>
                        </li>
                        <li><a href="form_upload.html">Form Upload</a>
                        </li>
                        <li><a href="form_buttons.html">Form Buttons</a>
                        </li>
                    </ul>
                </li>
                <li><a><i class="fa fa-desktop"></i> UI Elements <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu" style="display: none">
                        <li><a href="general_elements.html">General Elements</a>
                        </li>
                        <li><a href="media_gallery.html">Media Gallery</a>
                        </li>
                        <li><a href="typography.html">Typography</a>
                        </li>
                        <li><a href="icons.html">Icons</a>
                        </li>
                        <li><a href="glyphicons.html">Glyphicons</a>
                        </li>
                        <li><a href="widgets.html">Widgets</a>
                        </li>
                        <li><a href="invoice.html">Invoice</a>
                        </li>
                        <li><a href="inbox.html">Inbox</a>
                        </li>
                        <li><a href="calender.html">Calender</a>
                        </li>
                    </ul>
                </li>
                <li><a><i class="fa fa-table"></i> Tables <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu" style="display: none">
                        <li><a href="tables.html">Tables</a>
                        </li>
                        <li><a href="tables_dynamic.html">Table Dynamic</a>
                        </li>
                    </ul>
                </li>
                <li><a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu" style="display: none">
                        <li><a href="chartjs.html">Chart JS</a>
                        </li>
                        <li><a href="chartjs2.html">Chart JS2</a>
                        </li>
                        <li><a href="morisjs.html">Moris JS</a>
                        </li>
                        <li><a href="echarts.html">ECharts </a>
                        </li>
                        <li><a href="other_charts.html">Other Charts </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="menu_section">
            <h3>Live On</h3>
            <ul class="nav side-menu">
                <li><a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu" style="display: none">
                        <li><a href="e_commerce.html">E-commerce</a>
                        </li>
                        <li><a href="projects.html">Projects</a>
                        </li>
                        <li><a href="project_detail.html">Project Detail</a>
                        </li>
                        <li><a href="contacts.html">Contacts</a>
                        </li>
                        <li><a href="profile.html">Profile</a>
                        </li>
                    </ul>
                </li>
                <li><a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu" style="display: none">
                        <li><a href="page_404.html">404 Error</a>
                        </li>
                        <li><a href="page_500.html">500 Error</a>
                        </li>
                        <li><a href="plain_page.html">Plain Page</a>
                        </li>
                        <li><a href="login.html">Login Page</a>
                        </li>
                        <li><a href="pricing_tables.html">Pricing Tables</a>
                        </li>

                    </ul>
                </li>
                <li><a><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a>
                </li>
            </ul>
        </div>

    </div>
    <!-- /sidebar menu -->

    <!-- /menu footer buttons -->
    <div class="sidebar-footer hidden-small">
        <a data-toggle="tooltip" data-placement="top" title="Settings">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Lock">
            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Logout">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
        </a>
    </div>
    <!-- /menu footer buttons -->
</div>

polls/templates/polls/admin/page_500.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentallela Alela! | </title>

    <!-- Bootstrap core CSS -->

    <link href="css/bootstrap.min.css" rel="stylesheet">

    <link href="fonts/css/font-awesome.min.css" rel="stylesheet">
    <link href="css/animate.min.css" rel="stylesheet">

    <!-- Custom styling plus plugins -->
    <link href="css/custom.css" rel="stylesheet">
    <link href="css/icheck/flat/green.css" rel="stylesheet">


    <script src="js/jquery.min.js"></script>

    <!--[if lt IE 9]>
        <script src="../assets/js/ie8-responsive-file-warning.js"></script>
        <![endif]-->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

</head>


<body class="nav-md">

    <div class="container body">

        <div class="main_container">

            <!-- page content -->
            <div class="col-md-12">
                <div class="col-middle">
                    <div class="text-center">
                        <h1 class="error-number">500</h1>
                        <h2>Internal Server Error</h2>
                        <p>We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing. <a href="#">Report this?</a>
                        </p>
                        <div class="mid_center">
                            <h3>Search</h3>
                            <form>
                                <div class="col-xs-12 form-group pull-right top_search">
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Search for...">
                                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Go!</button>
                        </span>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /page content -->

        </div>
        <!-- footer content -->
    </div>

    <div id="custom_notifications" class="custom-notifications dsp_none">
        <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
        </ul>
        <div class="clearfix"></div>
        <div id="notif-group" class="tabbed_notifications"></div>
    </div>

    <script src="js/bootstrap.min.js"></script>

    <!-- chart js -->
    <script src="js/chartjs/chart.min.js"></script>
    <!-- bootstrap progress js -->
    <script src="js/progressbar/bootstrap-progressbar.min.js"></script>
    <script src="js/nicescroll/jquery.nicescroll.min.js"></script>
    <!-- icheck -->
    <script src="js/icheck/icheck.min.js"></script>

    <script src="js/custom.js"></script>

    <!-- /footer content -->
</body>

</html>